//---------------------------------------------------------------------
//  Copyright (C) Microsoft Corporation.  All rights reserved.
// 
//THIS CODE AND INFORMATION ARE PROVIDED AS IS WITHOUT WARRANTY OF ANY
//KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
//IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A
//PARTICULAR PURPOSE.
//---------------------------------------------------------------------

using DataGridViewAutoFilter;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.SqlClient;
using System.Drawing;
using System.Text;
using System.Windows.Forms;

namespace ProgrammaticSetupDemo
{

    public class MyClass
    {
        public string MyProperty { get; set; }
        public string MyProperty1 { get; set; }
        public string MyProperty2 { get; set; }

        public int OrderTotal { get; set; }
    }

    public class ProgrammaticSetupForm : Form
    {
        DataGridView dataGridView1 = new DataGridView();
        StatusStrip statusStrip1 = new StatusStrip();
        ToolStripStatusLabel filterStatusLabel = new ToolStripStatusLabel();
        ToolStripStatusLabel showAllLabel = new ToolStripStatusLabel("Show &All");

        // Initializes the form.
        public ProgrammaticSetupForm()
        {
            dataGridView1.Name = "dataGridView1";
            dataGridView1.Dock = DockStyle.Fill;
            dataGridView1.BindingContextChanged += new EventHandler(dataGridView1_BindingContextChanged);
            dataGridView1.KeyDown += new KeyEventHandler(dataGridView1_KeyDown);
            dataGridView1.DataBindingComplete +=
                new DataGridViewBindingCompleteEventHandler(
                dataGridView1_DataBindingComplete);

            showAllLabel.Visible = false;
            showAllLabel.IsLink = true;
            showAllLabel.LinkBehavior = LinkBehavior.HoverUnderline;
            showAllLabel.Click += new EventHandler(showAllLabel_Click);

            statusStrip1.Cursor = Cursors.Default;
            statusStrip1.Items.AddRange(new ToolStripItem[] {
                filterStatusLabel, showAllLabel });


            this.Text = "DataGridView AutoFilter Demo (C# Programmatic Setup)";
            this.Width *= 3;
            this.Height *= 2;
            this.Controls.AddRange(new Control[] {
                dataGridView1, statusStrip1 });
        }

        // Initializes the data source.
        protected override void OnLoad(EventArgs e)
        {
            DataTable data = new DataTable();
            data.ReadXmlSchema(@"..\..\..\..\..\TestData.xsd");
            data.ReadXml(@"..\..\..\..\..\TestData.xml");

            //List<MyClass> data = new List<MyClass>();
            //for (int i = 0; i < 1000; i++)
            //{
            //    data.Add(new MyClass
            //    {
            //        MyProperty = $"MyProperty{i}",
            //        MyProperty1 = $"MyProperty{i + 1}",
            //        MyProperty2 = $"MyProperty{i + 2}",
            //        OrderTotal = i
            //    }); ;
            //}

            BindingSource dataSource = new BindingSource(data, null);
            dataGridView1.DataSource = dataSource;
            base.OnLoad(e);
        }

        // Configures the autogenerated columns, replacing their header
        // cells with AutoFilter header cells. 
        private void dataGridView1_BindingContextChanged(object sender, EventArgs e)
        {
            // Continue only if the data source has been set.
            if (dataGridView1.DataSource == null)
            {
                return;
            }

            // Add the AutoFilter header cell to each column.
            foreach (DataGridViewColumn col in dataGridView1.Columns)
            {
                col.HeaderCell = new
                    DataGridViewAutoFilterColumnHeaderCell(col.HeaderCell);
            }

            // Format the OrderTotal column as currency. 
            dataGridView1.Columns["OrderTotal"].DefaultCellStyle.Format = "c";

            // Resize the columns to fit their contents.
            dataGridView1.AutoResizeColumns();
        }

        // Displays the drop-down list when the user presses 
        // ALT+DOWN ARROW or ALT+UP ARROW.
        private void dataGridView1_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.Alt && (e.KeyCode == Keys.Down || e.KeyCode == Keys.Up))
            {
                DataGridViewAutoFilterColumnHeaderCell filterCell =
                    dataGridView1.CurrentCell.OwningColumn.HeaderCell as
                    DataGridViewAutoFilterColumnHeaderCell;
                if (filterCell != null)
                {
                    filterCell.ShowDropDownList();
                    e.Handled = true;
                }
            }
        }

        // Updates the filter status label. 
        private void dataGridView1_DataBindingComplete(object sender,
            DataGridViewBindingCompleteEventArgs e)
        {
            String filterStatus = DataGridViewAutoFilterColumnHeaderCell
                .GetFilterStatus(dataGridView1);
            if (String.IsNullOrEmpty(filterStatus))
            {
                showAllLabel.Visible = false;
                filterStatusLabel.Visible = false;
            }
            else
            {
                showAllLabel.Visible = true;
                filterStatusLabel.Visible = true;
                filterStatusLabel.Text = filterStatus;
            }
        }

        // Clears the filter when the user clicks the "Show All" link
        // or presses ALT+A. 
        private void showAllLabel_Click(object sender, EventArgs e)
        {
            DataGridViewAutoFilterColumnHeaderCell.RemoveFilter(dataGridView1);
        }

    }
}